---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pricelist-ingress
  namespace: pricelist
spec:
  ingressClassName: traefik
  rules:
    - host: pricelist.minikube.mahagony4.me
      http:
        paths:
          - backend:
              service:
                name: pricelist
                port:
                  number: 8080
            path: /
            pathType: Prefix
