---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bgd-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: bgd.minikube.mahagony4.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bgd
                port:
                  number: 8080
...
